[package]
name = "mdstream"
version = "0.3.4"
description = "Streaming Markdown renderer for terminals"
edition = "2024"
rust-version = "1.94"
license = "MIT"
authors = ["Gaston Morixe <gaston@gastonmorixe.com>"]
homepage = "https://github.com/gastonmorixe/mdstream"
repository = "https://github.com/gastonmorixe/mdstream"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive", "env"] }
crossterm = "0.29.0"
regex = "1.12.3"
syntect = { version = "5.3.0", default-features = false, features = ["default-fancy"] }
unicode-width = "0.2.2"

[dev-dependencies]
insta = "1.46.3"
pretty_assertions = "1.4.1"
